### ISSUE TITLE
Make the plugin work for maps that are ungrouped in the workspace

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#11]
self explanitory, make the map selection automatically check the workspace for a map and if it does, automatically select that instead then go on to selecting a map.

**Comment by GlowingUmbreon** [comment]
It would be better to have it stored as a folder in workspace instead of in the workspace directly. It could cause issues if they have other things in workspace that are not related to the map.

**Comment by grif-0** [comment]
Probably a better way of going but then the map selection would be a bit weird because you can't just select a folder from the workspace and if possible I would like to not have to rely on the explorer to select models.

**Comment by grif-0** [comment]
Now supports models in the workspace, folders in the workspace, and ungrouped maps in the workspace.
