### ISSUE TITLE
Insert / "Plugin" Menu

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#2]
The insert tab will allow users to insert map kits (TRIA map kit), featured map additions, and easy addition of some map components.

You do not need to have a map selected to insert mapkits but you will to insert map additions and map components.

 - [x] Map components
 - [x] Map kits

 - [x] EasyTP integration
 - [x] TUNE integration
 - [x] Jump measurement integration
 - [x] Waterjet integration

**Comment by krypt102** [comment]
Waterjets done!
