### ISSUE TITLE
Make sure everything works with ChangeHistoryService

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#27]
as title says

 - [x] ObjectTags
 - [x] Settings
 - [x] Insert

**Comment by krypt102** [comment]
Wonder who _didn't_ do this :(

**Comment by grif-0** [comment]
1/2 of ObjectTags supports changehistoryservice; metadata parts are not made yet

**Comment by grif-0** [comment]
Settings + ObjectTags are good to go
