### ISSUE TITLE
Whitelisting + Map Publishing

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#3]
This will add a new tab to the plugin enabling map developers to whitelist and publish their maps directly from Roblox Studio. 

Developers will first need to join the map manager, create an API token linked to their account, and then input it into the plugin to allow players to publish + whitelist directly from Roblox Studio. 

Note: Sharing your token with other players may result in other players being able to whitelist/publish maps under your name. 

 - [x] Create UI 
 - [x] get UI to work
 - [ ] yell at Umbreon to do the stuff they need to do in the webserver part (token creation, whitelisting, publishing)
- [ ] Integrate the webserver functions with the plugin

**Comment by grif-0** [comment]
Emphasis on item 2 in the checklist

**Comment by krypt102** [comment]
Deferred for now until webserver is in a stable state.
