### ISSUE TITLE
MapLib Documentation

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#8]
This tab will contain information about the MapLib and EffectScript, and how they work. Understanding how to script a map is vital to making a good map.

Anything else we can think of will also get added here I feel like it needs more

 - [x] Full maplib documentation
 - [x] Script editor maplib autocomplete (not sure if possible)

**Comment by grif-0** [comment]
Not exactly sure how this would play out so closing this for the time being since there's a lot more that needs to be done. Will reopen if I get a solid idea on what this will do

**Comment by grif-0** [comment]
slightly revised but i still dont know exactly what this should be

**Comment by grif-0** [comment]
Audio library integration should also be a thing but not sure if these should be separated into 2 tabs

**Comment by krypt102** [comment]
Finished!

**Comment by krypt102** [comment]
(have created a new issue for the audio library)

**Comment by grif-0** [comment]
- [x] make autocomplete settings save to studio settings so it saves across places / sessions

**Comment by grif-0** [comment]
nvm it does this
